## You can use this simbols: î‚¶ î‚´ î‚² î‚° îƒ‚ îƒ€ îƒŠ îƒˆ îƒ‡ îƒ†  îƒŒ  îƒîƒ‘  îƒ” îƒ’

format = """
[ î‚¶](bg: fg:#ffffff)\
[ï ¼ ](bg:#ffffff fg:#000000)\
[î‚°](bg:#86BBD8 fg:#ffffff)\
$username\
[î‚°](bg:#DA627D fg:#86BBD8)\
$directory\
[î‚°](bg:#fc9369 fg:#DA627D)\
$git_branch\
$git_status\
[î‚°](fg:#fc9369 bg:#86BBD8)\
[\
$java\
$lua\
$python\
$nodejs\
$c\
$cpp\
$haskell\
$rust\
](bg:#86BBD8)\
[î‚°](fg:#86BBD8 bg:#06969A)\
$docker_context\
[î‚° ](fg:#06969A)
[ ]()\
[ î‚¶â–ˆâ–ˆî‚° ](bg:normal fg:white)
"""
# [ îŠ… ](fg:white)


right_format = """\
[î‚¶](fg:#33658A)
$time\
[î‚´ ](fg:#33658A)
"""


# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#86BBD8 fg:#000000"
style_root = "bg:cyan fg:red"
format = '[$user]($style)'

[directory]
style = "bg:#DA627D fg:#ffffff"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"lab" = "ï­§"
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[git_branch]
symbol = "ï˜"
style = "bg:#fc9369 fg:#ffffff"
format = '[ $symbol$branch]($style)'

[git_status]
style = "bg:#fc9369 fg:#ffffff"
format = '[$all_status$ahead_behind]($style)'

# Languages
[python]
symbol = "ğŸ"
style = "bg:#86BBD8 fg:#ffffff"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[java]
symbol = "î‰– "
style = "bg:#86BBD8 fg:#ffffff"
format = '[$symbol ($version) ]($style)'

[lua]
symbol = "ğŸŒ™ "
style = "bg:#86BBD8 fg:#ffffff"
format = '[$symbol($version )]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#86BBD8 fg:#ffffff"
format = '[$symbol ($version) ]($style)'

[c]
symbol = "î˜ "
style = "bg:#86BBD8 fg:#ffffff"
format = '[$symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#86BBD8 fg:#ffffff"
format = '[$symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A fg:#ffffff"
format = '[$symbol $context ]($style) $path'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A fg:#ffffff"
format = '[$time]($style)'
